image: openjdk:8-jdk


variables:
  ANDROID_COMPILE_SDK: "25"
  ANDROID_BUILD_TOOLS: "25.0.3"
  ANDROID_SDK_TOOLS: "25.2.5"
  ANDROID_SDK_TOOLS_REV: "3952940"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget unzip lib32stdc++6 lib32z1 bash
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS_REV}.zip
  - unzip -qq android-sdk.zip -d ${PWD}/android-sdk-linux
  - mkdir ${HOME}/.android
  - echo "count=0" > ${HOME}/.android/repositories.cfg
  - export ANDROID_HOME=${PWD}/android-sdk-linux
  - export PATH=$PATH:${ANDROID_HOME}/platform-tools
  - echo "${SHELL}"
  - export SHELL="/bin/bash"
  - echo "${SHELL}"
  - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager --update 
  - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "tools"
  - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "platform-tools"
  - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "build-tools;"$ANDROID_BUILD_TOOLS
  - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-"$ANDROID_COMPILE_SDK
  - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "extras;android;m2repository"
  - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "extras;google;google_play_services"
  - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "extras;google;m2repository"
  - chmod +x ./gradlew

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug --stacktrace
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_TAG}_${CI_COMMIT_SHA}"
    paths:
    - app/build/outputs/

unitTests:
  stage: test
  script:
    - ./gradlew test

functionalTests:
  stage: test
  script:
    - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
    - chmod +x android-wait-for-emulator
    - echo y | ${ANDROID_HOME}/tools/bin/sdkmanager "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86_64"
    - echo no | ${ANDROID_HOME}/tools/bin/avdmanager -s create avd -n test -k "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86_64"
    - ${ANDROID_HOME}/tools/emulator -avd test -no-window -no-audio &
    - ./android-wait-for-emulator
    - adb shell input keyevent 82
    - ./gradlew cAT
